blank_issues_enabled: true
contact_links:
  - name: Get Help
    url: https://github.com/epicweb-dev/config/discussions/new?category=q-a
    about:
      If you can't get something to work the way you expect, open a question in
      the discussions.
  - name: ESLint Rule Suggestion
    url: https://github.com/epicweb-dev/config/discussions/new
    about:
      We appreciate you taking the time to improve `@epic-web/config` with your
      ideas, but we use the Discussions for this instead of the issues tab ğŸ™‚.
  - name: ğŸ’¬ Epic Web Discord Server
    url: https://kcd.im/discord
    about: Interact with other Epic Web developers
  - name: ğŸ¿ Epic Web Tips
    url: https://www.epicweb.dev/tips
    about: Check out tips from Epic Instructors on EpicWeb.dev
